Website = "https://github.com/KJHJason/Cultured-Downloader"

[Details]
  Icon = "./res/icons/cultured-downloader-logo.png"
  Name = "Cultured Downloader"
  ID = "cultured.downloader"
  Version = "5.0.0"
  Build = 4
