from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver

# run this code if you do not have chromedriver.exe downloaded
# retrieve the exe path from the info generated by ChromeDriverManager
# then put the path in the webdriver intialization in the main python files
# e.g. driver = webdriver.Chrome(executable_path=r"<paste your path here>", options=chrome_options, desired_capabilities=capabilities)
driver = webdriver.Chrome(ChromeDriverManager().install())
driver.close()