blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://discord.com/users/338589106298683392
    about: If you have any requests for additional features, you can add me on discord at Dratornic#0101