blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/KJHJason/Cultured-Downloader/discussions
    about: If you have any requests for additional features, please use the Discussions tab instead. Thanks!