blank_issues_enabled: true
contact_links:
  - name: Want updates on Cultured Downloader?
    url: https://github.com/KJHJason/Cultured-Downloader/discussions
    about: If you want to know the progress of Cultured Downloader, updates are ocassionally posted in the discussions tab.
