name: パスワード検出ミス
description: 投稿にパスワードがあるのにログされていない場合は、こちらでパスワード検出ミスの報告をしてください。「(ウェブサイト)」をパスワード検出ミスが発生したウェブサイトに変更してください。
title: "(ウェブサイト) のパスワード検出ミス"
labels: ["enhancement"]
assignees: 
  - KJHJason

body:
  - type: markdown
    attributes:
      value: |
        パスワード検出ミスの報告にご協力いただき、ありがとうございました！パスワード検出システムの改善に役立ちます。

  - type: dropdown
    id: platform
    attributes:
      label: ウェブサイト
      description: どのウェブサイトの投稿ですか？
      multiple: true
      options:
        - Fantia
        - Pixiv
        - Pixiv Fanbox
        - Kemono
    validations:
      required: true

  - type: input
    id: post_url
    attributes:
      label: 投稿URL
      description: パスワードが検出されなかった投稿のURLは何ですか？
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: パスワードのスクリーンショット
      description: 可能であれば、投稿内容にあるパスワードのスクリーンショットを提供してください。（ここに画像をドラッグアンドドロップできます）
