name: Password Detection Misses
description: "Password not logged despite being present in the post? File a password detection miss report here. Note: Please change \"(platform)\" to the platform where the password detection miss occurred."
title: "Password Detection Miss for (platform)"
labels: ["enhancement"]
assignees: 
  - KJHJason

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this password detection miss report! It helps to improve the password detection system.

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform was the post(s) from?
      multiple: true
      options:
        - Fantia
        - Pixiv
        - Pixiv Fanbox
        - Kemono
    validations:
      required: true

  - type: input
    id: post_url
    attributes:
      label: Post URL
      description: What is the URL of the post where the password was not detected?
    validations:
      required: true

  - type: input
    id: screenshot
    attributes:
      label: Screenshot of the Post
      description: If possible, please provide a screenshot of the password that is on the post content. (You can drag and drop the image here)
