name: Translation Error
description: Found a translation error? Report it here!
title: "Translation Error: "
labels: ["translation error"]
assignees: 
  - KJHJason

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this translation error report! If you found a translation error in Cultured Downloader, feel free to share it here.

  - type: input
    id: program_version
    attributes:
      label: Program Version
      description: What version of the program are you using? (Can be found in the program info tab under settings)
    validations:
      required: true

  - type: textarea
    id: translation_error
    attributes:
      label: Translation Error
      description: Describe the translation error you found and suggest the translation that should be used instead.
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: Paste a screenshot of the translation error here so that I can locate the source of the translation error.
