// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckMasterPassword(arg1) {
  return window['go']['app']['App']['CheckMasterPassword'](arg1);
}

export function GetName() {
  return window['go']['app']['App']['GetName']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function PromptMasterPassword() {
  return window['go']['app']['App']['PromptMasterPassword']();
}

export function ResetEncryptedFields() {
  return window['go']['app']['App']['ResetEncryptedFields']();
}
