// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelQueue(arg1) {
  return window['go']['app']['App']['CancelQueue'](arg1);
}

export function ChangeMasterPassword(arg1, arg2) {
  return window['go']['app']['App']['ChangeMasterPassword'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function CheckMasterPassword(arg1) {
  return window['go']['app']['App']['CheckMasterPassword'](arg1);
}

export function DeleteProfilePic() {
  return window['go']['app']['App']['DeleteProfilePic']();
}

export function DeleteQueue(arg1) {
  return window['go']['app']['App']['DeleteQueue'](arg1);
}

export function GetDarkMode() {
  return window['go']['app']['App']['GetDarkMode']();
}

export function GetDownloadDir() {
  return window['go']['app']['App']['GetDownloadDir']();
}

export function GetDownloadQueues() {
  return window['go']['app']['App']['GetDownloadQueues']();
}

export function GetFfmpegPath() {
  return window['go']['app']['App']['GetFfmpegPath']();
}

export function GetGDriveAPIKey() {
  return window['go']['app']['App']['GetGDriveAPIKey']();
}

export function GetGDriveServiceAccount() {
  return window['go']['app']['App']['GetGDriveServiceAccount']();
}

export function GetGdriveClient() {
  return window['go']['app']['App']['GetGdriveClient']();
}

export function GetLanguage() {
  return window['go']['app']['App']['GetLanguage']();
}

export function GetPixivRefreshToken() {
  return window['go']['app']['App']['GetPixivRefreshToken']();
}

export function GetPreferences() {
  return window['go']['app']['App']['GetPreferences']();
}

export function GetProfilePic() {
  return window['go']['app']['App']['GetProfilePic']();
}

export function GetProgramInfo() {
  return window['go']['app']['App']['GetProgramInfo']();
}

export function GetSessionValue(arg1) {
  return window['go']['app']['App']['GetSessionValue'](arg1);
}

export function GetUserAgent() {
  return window['go']['app']['App']['GetUserAgent']();
}

export function GetUsername() {
  return window['go']['app']['App']['GetUsername']();
}

export function HasProfilePic() {
  return window['go']['app']['App']['HasProfilePic']();
}

export function PromptMasterPassword() {
  return window['go']['app']['App']['PromptMasterPassword']();
}

export function RemoveMasterPassword() {
  return window['go']['app']['App']['RemoveMasterPassword']();
}

export function ResetSession(arg1) {
  return window['go']['app']['App']['ResetSession'](arg1);
}

export function SelectDlDirPath() {
  return window['go']['app']['App']['SelectDlDirPath']();
}

export function SelectFfmpegPath() {
  return window['go']['app']['App']['SelectFfmpegPath']();
}

export function SelectGDriveServiceAccount() {
  return window['go']['app']['App']['SelectGDriveServiceAccount']();
}

export function SelectProfilePic() {
  return window['go']['app']['App']['SelectProfilePic']();
}

export function SetDarkMode(arg1) {
  return window['go']['app']['App']['SetDarkMode'](arg1);
}

export function SetDlDirPath(arg1) {
  return window['go']['app']['App']['SetDlDirPath'](arg1);
}

export function SetFfmpegPath(arg1) {
  return window['go']['app']['App']['SetFfmpegPath'](arg1);
}

export function SetGDriveAPIKey(arg1) {
  return window['go']['app']['App']['SetGDriveAPIKey'](arg1);
}

export function SetGeneralPreferences(arg1) {
  return window['go']['app']['App']['SetGeneralPreferences'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}

export function SetMasterPassword(arg1) {
  return window['go']['app']['App']['SetMasterPassword'](arg1);
}

export function SetPixivOAuthRefreshToken(arg1) {
  return window['go']['app']['App']['SetPixivOAuthRefreshToken'](arg1);
}

export function SetPixivPreferences(arg1) {
  return window['go']['app']['App']['SetPixivPreferences'](arg1);
}

export function SetSessionValue(arg1, arg2) {
  return window['go']['app']['App']['SetSessionValue'](arg1, arg2);
}

export function SetUserAgent(arg1) {
  return window['go']['app']['App']['SetUserAgent'](arg1);
}

export function SetUsername(arg1) {
  return window['go']['app']['App']['SetUsername'](arg1);
}

export function StartPixivOAuth() {
  return window['go']['app']['App']['StartPixivOAuth']();
}

export function SubmitFantiaToQueue(arg1, arg2) {
  return window['go']['app']['App']['SubmitFantiaToQueue'](arg1, arg2);
}

export function SubmitKemonoToQueue(arg1, arg2) {
  return window['go']['app']['App']['SubmitKemonoToQueue'](arg1, arg2);
}

export function SubmitPixivFanboxToQueue(arg1, arg2) {
  return window['go']['app']['App']['SubmitPixivFanboxToQueue'](arg1, arg2);
}

export function UnsetGDriveServiceAccount() {
  return window['go']['app']['App']['UnsetGDriveServiceAccount']();
}

export function UploadCookieFile(arg1) {
  return window['go']['app']['App']['UploadCookieFile'](arg1);
}

export function UploadProfilePic(arg1) {
  return window['go']['app']['App']['UploadProfilePic'](arg1);
}

export function ValidateFantiaUrls(arg1) {
  return window['go']['app']['App']['ValidateFantiaUrls'](arg1);
}

export function ValidateKemonoUrls(arg1) {
  return window['go']['app']['App']['ValidateKemonoUrls'](arg1);
}

export function ValidatePixivFanboxUrls(arg1) {
  return window['go']['app']['App']['ValidatePixivFanboxUrls'](arg1);
}

export function VerifyPixivOAuthCode(arg1) {
  return window['go']['app']['App']['VerifyPixivOAuthCode'](arg1);
}
