// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {gdrive} from '../models';
import {appdata} from '../models';

export function ChangeMasterPassword(arg1:string,arg2:string):Promise<void>;

export function CheckMasterPassword(arg1:string):Promise<boolean>;

export function DeleteProfilePic():Promise<void>;

export function DeleteQueue(arg1:number):Promise<void>;

export function GetDarkMode():Promise<boolean>;

export function GetDownloadDir():Promise<string|boolean>;

export function GetDownloadQueues():Promise<Array<app.FrontendDownloadQueue>>;

export function GetGdriveClient():Promise<gdrive.GDrive>;

export function GetLanguage():Promise<string>;

export function GetPreferences():Promise<appdata.Preferences>;

export function GetProfilePic():Promise<app.ProfilePic>;

export function GetUsername():Promise<string>;

export function HasProfilePic():Promise<boolean>;

export function PromptMasterPassword():Promise<boolean>;

export function RemoveMasterPassword():Promise<void>;

export function SelectProfilePic():Promise<app.ProfilePic>;

export function SetDarkMode(arg1:boolean):Promise<void>;

export function SetLanguage(arg1:string):Promise<string>;

export function SetMasterPassword(arg1:string):Promise<void>;

export function SetPreferences(arg1:string,arg2:appdata.Preferences):Promise<void>;

export function SetUsername(arg1:string):Promise<void>;

export function SubmitFantiaToQueue(arg1:Array<string>,arg2:{[key: string]: boolean}):Promise<void>;

export function UploadProfilePic(arg1:string):Promise<void>;

export function ValidateFantiaUrls(arg1:Array<string>):Promise<boolean>;
