// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelQueue(arg1) {
  return window['go']['app']['App']['CancelQueue'](arg1);
}

export function ChangeMasterPassword(arg1, arg2) {
  return window['go']['app']['App']['ChangeMasterPassword'](arg1, arg2);
}

export function CheckMasterPassword(arg1) {
  return window['go']['app']['App']['CheckMasterPassword'](arg1);
}

export function GetDarkMode() {
  return window['go']['app']['App']['GetDarkMode']();
}

export function GetName() {
  return window['go']['app']['App']['GetName']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function NewDownloadQueue(arg1, arg2) {
  return window['go']['app']['App']['NewDownloadQueue'](arg1, arg2);
}

export function PromptMasterPassword() {
  return window['go']['app']['App']['PromptMasterPassword']();
}

export function ResetEncryptedFields() {
  return window['go']['app']['App']['ResetEncryptedFields']();
}

export function SetDarkMode(arg1) {
  return window['go']['app']['App']['SetDarkMode'](arg1);
}

export function SetMasterPassword(arg1) {
  return window['go']['app']['App']['SetMasterPassword'](arg1);
}
