// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {gdrive} from '../models';
import {database} from '../models';

export function CancelGDriveOauth():Promise<void>;

export function CancelQueue(arg1:number):Promise<void>;

export function ChangeMasterPassword(arg1:string,arg2:string):Promise<void>;

export function CheckForUpdates():Promise<boolean>;

export function CheckMasterPassword(arg1:string):Promise<boolean>;

export function DeleteAllGdriveCache():Promise<void>;

export function DeleteAllKemonoCreatorCache():Promise<void>;

export function DeleteAllPostCache():Promise<void>;

export function DeleteAllUgoiraCache():Promise<void>;

export function DeleteCacheKey(arg1:string,arg2:string):Promise<void>;

export function DeleteProfilePic():Promise<void>;

export function DeleteQueue(arg1:number):Promise<void>;

export function GetAllGdriveCache():Promise<Array<app.FrontendCacheKeyValue>>;

export function GetAllKemonoCreatorCache():Promise<Array<app.FrontendCacheKeyValue>>;

export function GetAllUgoiraCache():Promise<Array<app.FrontendCacheKeyValue>>;

export function GetDarkMode():Promise<boolean>;

export function GetDownloadDir():Promise<string>;

export function GetDownloadQueues():Promise<Array<app.FrontendDownloadQueue>>;

export function GetFfmpegPath():Promise<string>;

export function GetFrontendDownloadDetails(arg1:number):Promise<Array<app.FrontendDownloadDetails>>;

export function GetGDriveAPIKey():Promise<string>;

export function GetGDriveClientAndOauthToken():Promise<app.GetGDriveOauthResponse>;

export function GetGDriveServiceAccount():Promise<string>;

export function GetGdriveClient():Promise<gdrive.GDrive>;

export function GetLanguage():Promise<string>;

export function GetPixivRefreshToken():Promise<string>;

export function GetPostCache(arg1:app.Filter):Promise<Array<database.PostCache>>;

export function GetPreferences():Promise<app.Preferences>;

export function GetProfilePic():Promise<app.ProfilePic>;

export function GetProgramInfo():Promise<app.ProgramInfo>;

export function GetSessionValue(arg1:string):Promise<string>;

export function GetUserAgent():Promise<app.UserAgentResponse>;

export function GetUsername():Promise<string>;

export function HasProfilePic():Promise<boolean>;

export function PromptMasterPassword():Promise<boolean>;

export function RemoveMasterPassword():Promise<void>;

export function ResetSession(arg1:string):Promise<void>;

export function SelectDlDirPath():Promise<void>;

export function SelectFfmpegPath():Promise<void>;

export function SelectGDriveServiceAccount():Promise<void>;

export function SelectProfilePic():Promise<app.ProfilePic>;

export function SetDarkMode(arg1:boolean):Promise<void>;

export function SetDlDirPath(arg1:string):Promise<void>;

export function SetFantiaPreferences(arg1:app.FantiaPreferences):Promise<void>;

export function SetFfmpegPath(arg1:string):Promise<void>;

export function SetGDriveAPIKey(arg1:string):Promise<void>;

export function SetGeneralPreferences(arg1:app.GeneralPreferences):Promise<void>;

export function SetLanguage(arg1:string):Promise<string>;

export function SetMasterPassword(arg1:string):Promise<void>;

export function SetPixivOAuthRefreshToken(arg1:string):Promise<void>;

export function SetPixivPreferences(arg1:app.PixivPreferences):Promise<void>;

export function SetSessionValue(arg1:string,arg2:string):Promise<void>;

export function SetUserAgent(arg1:string):Promise<void>;

export function SetUsername(arg1:string):Promise<void>;

export function StartGDriveOauth():Promise<void>;

export function StartPixivOAuth():Promise<string>;

export function SubmitFantiaToQueue(arg1:Array<string>,arg2:app.Preferences):Promise<void>;

export function SubmitKemonoToQueue(arg1:Array<string>,arg2:app.Preferences):Promise<void>;

export function SubmitPixivFanboxToQueue(arg1:Array<string>,arg2:app.Preferences):Promise<void>;

export function SubmitPixivToQueue(arg1:Array<string>,arg2:app.Preferences):Promise<void>;

export function Translate(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UnsetGDriveJson():Promise<void>;

export function UploadCookieFile(arg1:string):Promise<void>;

export function UploadProfilePic(arg1:string):Promise<void>;

export function ValidateFantiaUrls(arg1:Array<string>):Promise<boolean>;

export function ValidateGDriveOauth():Promise<void>;

export function ValidateKemonoInputs(arg1:Array<string>):Promise<boolean>;

export function ValidatePixivFanboxUrls(arg1:Array<string>):Promise<boolean>;

export function ValidatePixivInputs(arg1:Array<string>):Promise<boolean>;

export function VerifyPixivOAuthCode(arg1:string):Promise<void>;
